### ISSUE TITLE
Support partial packages

### ISSUE THREAD

**Issue by Androz2091** [dumpus-app/dumpus-app#197]
**New package_is_partial column**

https://github.com/dumpus-app/dumpus-api/blob/main/docs/sqlite_database_structure.md?plain=1#L81

If set to 1, we should hide:

in the "sheer numbers", the cards:
* server joined
* received calls
* Discord app started count

In the "stats" page, the cards:
* all the small cards at the bottom
* joined servers
* average session count
* app starts

**Comment by florian-lefebvre** [comment]
I wish it was directly a boolean
