### ISSUE TITLE
Enable dragging on horizontal scroll areas on desktop/web

### ISSUE THREAD

**Issue by Androz2091** [dumpus-app/dumpus-app#203]
Suggestion for desktop: be able to slide these views like you can on mobile. You can manually click the scrollbar on desktop, but that's a bit annoying, especially when it's that small.

https://github.com/dumpus-app/dumpus-app/assets/42497995/ab384250-3e23-4e5d-8e0f-bf3d3b975e93

**Comment by florian-lefebvre** [comment]
We need to check a few things:
- We can make the scrollbar bigger
- We need to investigate [Radix-UI docs](https://www.radix-ui.com/docs/primitives/components/scroll-area)
- Do we need another library? Like swiper
