### ISSUE TITLE
Update settings Discord link

### ISSUE THREAD

**Issue by MampoX** [dumpus-app/dumpus-app#219]
The link to the community server is redirecting us to the Discord website instead.! [Polish_20230719_212636162.png](https://github.com/dumpus-app/dumpus-app/assets/118007887/abf0fe5e-cf9c-4b3e-94a7-ed29614ec363)

**Comment by florian-lefebvre** [comment]
https://github.com/dumpus-app/dumpus-app/blob/main/src/app/[locale]/(app)/settings/_components/About.tsx#L39

**Comment by Androz2091** [comment]
It's updated 👍 
will be fixed by v0.0.14
