### ISSUE TITLE
Share image shows wrong datas

### ISSUE THREAD

**Issue by MampoX** [dumpus-app/dumpus-app#222]
The image when you want to share it, shows wrong datas of your account. I don't know if it's on purpose or not, but if it's not, it may cause some problems.! [Polish_20230719_214224919.png](https://github.com/dumpus-app/dumpus-app/assets/118007887/21f15543-8e9a-4dc9-bf93-ac8a3ef189b9)

**Comment by Androz2091** [comment]
I think it depends on the time range you select right? if you select "lifetime" in the "stats" page and go back to overview, you will see the right number?

**Comment by MampoX** [comment]
I don't, I'll check.

**Comment by MampoX** [comment]
You were right! It works depending on what stats you have selected.

**Comment by Androz2091** [comment]
maybe we could share a different static card depending on the time range selection 🤔 
won't be done before v1 though

**Comment by MampoX** [comment]
Yes, it could be better and less confusing for users

**Comment by florian-lefebvre** [comment]
Closed by #235
