### ISSUE TITLE
Changing period only updates "messages sent", not other categories

### ISSUE THREAD

**Issue by mariusbegby** [dumpus-app/dumpus-app#230]
Changing period only updates "messages sent", not other categories.

4 weeks period:
<img width="763" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/e6208377-3f81-414d-819a-00f5f1c6a0d0">

Lifetime period:
<img width="767" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/5f647d96-59cf-46c8-a21a-b0d51a918db7">

As seen, only message count is updated.

Demo data package (wumpus) works fine. This only happens to my real data package.

This info also stays the same:
<img width="775" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/d5df7204-272c-4a9b-8948-94ef2aed0204">
<img width="719" alt="image" src="https://github.com/dumpus-app/dumpus-app/assets/25694918/336aaf85-b352-4850-a0f7-5bdac61cb750">

Same in version v0.0.13-web (prod) and v0.0.11-web (prod) from dev-preview. Still not updating on page refresh etc.

**Comment by florian-lefebvre** [comment]
@Androz2091 do you think it's an issue in the app or the api? if it works for the demo I don't see why it wouldn't work here on the frontend side

**Comment by mariusbegby** [comment]
As discussed over on Discord, most likely related to this tick that i just toggled on around 2023-07-04:
![image](https://github.com/dumpus-app/dumpus-app/assets/25694918/39a9c9a1-72f7-4789-8fc0-5dd76e0a9079)

And the data that only shows for "last 4 weeks" is because Discord didn't collect that data before this moment.

Suggestion:
- Handle this case and display message to user "Only showing data from (date) because of ..."

**Comment by florian-lefebvre** [comment]
How are we supposed to detect this, just if there is no data? Or is there a better way?

**Comment by Androz2091** [comment]
superseded by #232
