### ISSUE TITLE
Some avatars do not show in the recap image

### ISSUE THREAD

**Issue by LukeIsHereToDevelop** [dumpus-app/dumpus-app#238]
Checking the console, I've seen that it's mostly because of the avatars being in .webp or .gif format.
I could suggest you to change the extension at the end of the avatar URLs to fix it, as it's a Discord CDN's feature.

My recap image:
![dumpus-share (2) (1)](https://github.com/dumpus-app/dumpus-app/assets/43251906/833a0468-75ba-47b1-937a-7eddaaf000ad)

**Comment by florian-lefebvre** [comment]
Thanks for reporting! I think it's a regression introduced by #198. In src/components/StaticShareCard (or whatever it's called), we should use the default Image component from next.
You can do it or @skdhg

**Comment by skdhg** [comment]
I think it's an issue with the usage of a "gif" format. Non gif avatars show up correctly. Could you assign me to this issue?

**Comment by LukeIsHereToDevelop** [comment]
I think it happens with avatars in .webp format to. My profile picture is not animated, it's in webp format.
