### ISSUE TITLE
Safe area should match the theme color

### ISSUE THREAD

**Issue by Mr-KayJayDee** [dumpus-app/dumpus-app#240]
In the screenshots you can see that the top and bottom of the screen are not colored and it feels weird. 

![Screenshot_2023-07-21-09-02-36-12_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/293dbfb8-b25a-4ac7-b63d-eea8f5cb8b92)

Example of safe area matching the color :

![Screenshot_2023-07-21-09-06-32-05_8ee8015dd2b473d44c46c2d8d6942cec.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/1c2fa958-b1db-4a04-bc15-45dc82270f8b)

Device infos

![Screenshot_2023-07-21-09-19-04-64_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/70de8808-dc8f-4fae-88f2-63b80c55713e)

**Comment by florian-lefebvre** [comment]
mmmh that's weird. We're setting them to transparent. What's your Android version?

**Comment by Androz2091** [comment]
Closed by 843b68442bd589e0ab4e6a78d3352e5975c98094

it was due to some not working plugin implementations

**Comment by florian-lefebvre** [comment]
Some stuff was required in the MainActivity.java file though (the overscroll behavior)

**Comment by florian-lefebvre** [comment]
When it's done, close the issue @Androz2091

**Comment by Androz2091** [comment]
we should be good
