### ISSUE TITLE
Unable to share recap

### ISSUE THREAD

**Issue by Mr-KayJayDee** [dumpus-app/dumpus-app#241]
When generating recap and clicking download the popup just closes and nothing opens.

https://github.com/dumpus-app/dumpus-app/assets/46600662/9d1eb4e6-7083-4535-89b4-0f5d54cdb7cb

![Screenshot_2023-07-21-09-19-04-64_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/a3f7e443-79fa-4112-be71-bbae6440e97f)

**Comment by Mr-KayJayDee** [comment]
The web sharing button does not work neither

`Intl.Segmenter does not exist, please use import a polyfill.`

**Comment by Mr-KayJayDee** [comment]
Here are more details

![image](https://github.com/dumpus-app/dumpus-app/assets/46600662/80afa752-a225-422d-8069-3896f37c0687)

I tried my best to find a way to fix it but found nothing, if you have time @florian-lefebvre can you look at it ? ^^

**Comment by florian-lefebvre** [comment]
I never encountered this error, can you check on satori's repo?

**Comment by skdhg** [comment]
> I never encountered this error, can you check on satori's repo?

Looks like firefox does not have `Intl.Segmenter` which causes this issue.

Chromium Browsers:
![image](https://github.com/dumpus-app/dumpus-app/assets/46562212/87a70de2-d399-40d2-a927-f5bc22338895)

Firefox:
![image](https://github.com/dumpus-app/dumpus-app/assets/46562212/5dd51ad4-9187-4ef1-a62d-13bb93fb1cfc)

This is true according to mdn

![image](https://github.com/dumpus-app/dumpus-app/assets/46562212/9daeeb7c-3e9e-43b5-99e7-4557e49385cf)

**Comment by florian-lefebvre** [comment]
Actually, here is how it's going to work:
- if the app is in a mobile app (android/ios **app**), then it will use Share.share from capacitor
- If in browser but supports the share api, then it will use navigator.share
- Else, offers to download

**Comment by Mr-KayJayDee** [comment]
Download or copy to clipboard? Can be both
