### ISSUE TITLE
Icons overlapping on iOS

### ISSUE THREAD

**Issue by Hunam6** [dumpus-app/dumpus-app#251]
When enlarging the setup images on iOS the top right icons are overlapping
![E5DE247C-0BF7-4F85-AAA5-998B82F1C23F](https://github.com/dumpus-app/dumpus-app/assets/38606542/678f539e-d60e-4bd0-bccb-3d1f16be0df5)

**Comment by florian-lefebvre** [comment]
Duplicate of #191
