### ISSUE TITLE
Hide Android & Desktop in setup if the app is running on iOS

### ISSUE THREAD

**Issue by Androz2091** [dumpus-app/dumpus-app#270]
We need to hide the button for the other platforms if the app is running on iOS in the onboarding setup (because Apple refuses it when submitting 🙂)

**we should only do this for iOS. and we should keep the three buttons iOS, Android, Desktop if the app is running on something else**

![Screenshot-0720-131427](https://github.com/dumpus-app/dumpus-app/assets/42497995/d9b170e3-193e-4102-accd-83b4cfb0667d)

**Comment by Androz2091** [comment]
![Capture d’écran 2023-07-23 à 12 16 27](https://github.com/dumpus-app/dumpus-app/assets/42497995/c1851434-d61f-45ea-9461-9ac6e4384897)
(expected)

**Comment by florian-lefebvre** [comment]
Yep I saw the review, that's stupid but anyway, I'll take care of that
