### ISSUE TITLE
implement statistics/analytics

### ISSUE THREAD

**Issue by Androz2091** [dumpus-app/dumpus-app#274]
@florian-lefebvre what do you think we should be using? a simple Umami or similar analytics tool?

**Comment by florian-lefebvre** [comment]
Yes I think that's enough. Would be could to have a public embed like Plausible to be really transparent

**Comment by Androz2091** [comment]
You mean show the statistics to everyone?

**Comment by florian-lefebvre** [comment]
Yep but as you wish

**Comment by Androz2091** [comment]
Yes we can do that
Can you setup this?

<script async defer data-website-id="8a05d592-7263-446f-a318-41f7b5087115" src="https://analytics.androz2091.fr/umami.js"></script>

the src and website id should be in the env file

no proxy and it does not matter if we are blocked by some chrome extensions (as we can't do any proxy as everything is client side)

**Comment by florian-lefebvre** [comment]
Sure 👍 I'll make sure it's not included on mobile or desktop

**Comment by skdhg** [comment]
> Yes we can do that Can you setup this?
> 
> <script async defer data-website-id="8a05d592-7263-446f-a318-41f7b5087115" src="https://analytics.androz2091.fr/umami.js"></script>
> the src and website id should be in the env file
> 
> no proxy and it does not matter if we are blocked by some chrome extensions (as we can't do any proxy as everything is client side)

might be worth using this instead: https://nextjs.org/docs/app/building-your-application/optimizing/scripts#offloading-scripts-to-a-web-worker-experimental

**Comment by florian-lefebvre** [comment]
Good idea

**Comment by florian-lefebvre** [comment]
cc @Androz2091 
```env
NEXT_PUBLIC_ANALYTICS_WEBSITE_ID="8a05d592-7263-446f-a318-41f7b5087115"
NEXT_PUBLIC_ANALYTICS_SRC="https://analytics.androz2091.fr/umami.js"
```
