### ISSUE TITLE
The version shown in app is wrong

### ISSUE THREAD

**Issue by MampoX** [dumpus-app/dumpus-app#277]
I updated my app to 0.0.17 and on the app it says I'm on 0.0.16.
[Polish_20230725_221741091.jpg](https://github.com/dumpus-app/dumpus-app/assets/118007887/a5014200-5f76-4bce-9947-67558f7358e0)

**Comment by florian-lefebvre** [comment]
Do you think the app you build and deploy is the one before version Code and version update @Androz2091 ?

**Comment by Androz2091** [comment]
try to update again @MampoX 

I'm sure it works on Google Play and iOS
