### ISSUE TITLE
Scroll restoration not always working

### ISSUE THREAD

**Issue by Androz2091** [dumpus-app/dumpus-app#279]
"Can you make it so it doesn't go at the beginning of the list in Top? If I press on a person and then I press the Back button it goes automatically on top of the list and I have to scroll again"

**Comment by Mr-KayJayDee** [comment]
For the other way if I click on a channel details for example I'm not at the top even if it's the first time I clicked the channel.

This is the case for channels, users, servers

![Screenshot_2023-07-26-02-50-16-28_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/81a51f6d-4c0b-48a3-9207-d740034a654c)

![Screenshot_2023-07-26-02-50-26-30_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/af904ab3-b233-4792-9bab-1046e1c9f47a)

![Screenshot_2023-07-26-02-50-22-10_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/e762e05c-9924-4c56-bb48-e0e77dc04c16)


Example: Scroller jusqu'à avoir chiffre clés tout en haut, cliquer sur more et constater que le scroll est pas au bon endroit 

![Screenshot_2023-07-26-02-51-16-70_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/2dc4247a-0d76-417b-a075-3a517ee754cf)

![Screenshot_2023-07-26-02-51-21-18_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/62a33f1f-a1fb-4451-81c3-a9dcfbef4dd8)

![Screenshot_2023-07-26-02-52-06-09_092e4e860d9d52d9f4e1cc64901c7bf3.jpg](https://github.com/dumpus-app/dumpus-app/assets/46600662/cf247467-406d-406b-bfb0-ddbe9c4ffdc7)
