### ISSUE TITLE
Do not always show Early Supporter pop-up 

### ISSUE THREAD

**Issue by Androz2091** [dumpus-app/dumpus-app#283]
At the moment, the Early Supporter window can appear at any time (usually when you restart the app and wait a few seconds, it shows the pop-up).

It should only be shown...:
- if the user clicked on "Restore purchases"
- if the user has just made the purchase

**Comment by florian-lefebvre** [comment]
I think it's a bug with the purchase module that calls product.approved at startup. We'll see

**Comment by florian-lefebvre** [comment]
https://github.com/j3k0/cordova-plugin-purchase/issues/1428

**Comment by Androz2091** [comment]
make sure it shows up when the restore purchase is cliekd
