### ISSUE TITLE
Loading chunk 5971 failed

### ISSUE THREAD

**Issue by Hunam6** [dumpus-app/dumpus-app#305]
- First AppStore version
![image](https://github.com/dumpus-app/dumpus-app/assets/38606542/4fd566df-a4a4-4575-869c-11dbf7f7b818)

**Comment by florian-lefebvre** [comment]
I don't have a mac to test until Thursday unfortunately. In the meantime, can you share some details:
1. What actions did you do? (like which page, or is it directly after opening)
2. Your iOS version?

**Comment by Androz2091** [comment]
Correct me if I'm wrong but:
- iOS is under 16.4
- just before the overview is shown

**Comment by Androz2091** [comment]
(that's what he said to me in DMs right after opening the issue)

**Comment by Hunam6** [comment]
@Androz2091 you got it right, my precise iOS version is 16.1.2

**Comment by florian-lefebvre** [comment]
That's so weird, satori 0.10.2 is installed with the patch but looks like it has no effect. I'll investigate on Thursday

**Comment by florian-lefebvre** [comment]
After checking `node_modules/satori/dist/index.js`, I can confirm patch is in the file so it should work. I'll test on ios ASAP

**Comment by florian-lefebvre** [comment]
It only happens in prod for some reason :/ will investigate more

**Comment by florian-lefebvre** [comment]
It does not happen on web.dumpus.app, safari (ios < 16.4) either 🤔. @Hunam6 can you just confirm your app version?

**Comment by florian-lefebvre** [comment]
I think it's caused by https://github.com/vercel/satori/blob/main/src/yoga/index.ts#L19. Trying to fix things with `transpilePackages`

**Comment by Hunam6** [comment]
> It does not happen on web.dumpus.app, safari (ios < 16.4) either 🤔. @Hunam6 can you just confirm your app version?

I don't know how to check for app version because I think you've only published one version to the AppStore, but anyway the AppStore doesn't allow any update.

**Comment by florian-lefebvre** [comment]
Alright no worries! I'm working on a fix rn 👍

**Comment by florian-lefebvre** [comment]
Good news @Hunam6, waiting on #315 to be merged!
