### ISSUE TITLE
web version: link invalid

### ISSUE THREAD

**Issue by Variable1485** [dumpus-app/dumpus-app#343]
putting the data package link gives a link invalid error even though its the correct click.discord link from the email (loads package normally)

**Comment by AsthmaQueen** [comment]
likewise having this issue

**Comment by VGmaster670** [comment]
+1

**Comment by Mixarar** [comment]
The discord changed their data package format, so I suppose its from that. Have to wait for a fix

**Comment by Androz2091** [comment]
@Mixarar @VGmaster670 @AsthmaQueen @Variable1485 it should be fixed, can you retry?

**Comment by VGmaster670** [comment]
Seems to be working, it didn't give an error about the link being invalid this time

**Comment by Variable1485** [comment]
Works now, thanks!
