### ISSUE TITLE
Dumpus gives "An unknown error occured."

### ISSUE THREAD

**Issue by Variable1485** [dumpus-app/dumpus-app#344]
After entering package link app gives error during analyzing in the android app and on the web version

**Comment by Androz2091** [comment]
Hello, what's the date your package was received at?

**Comment by Androz2091** [comment]
I mean, when was it sent by discord?

**Comment by Variable1485** [comment]
3/7/2024, shouldn't expire yet.

**Comment by Androz2091** [comment]
Yep but they changed the format on March, 10th. You can use ddpe in the meantime

**Comment by Variable1485** [comment]
Ah, thanks for the explanation!
