### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by DarkPizza** [dumpus-app/dumpus-app#354]
Performing an error while trying to load my data to Dumpus

`Access to fetch at 'https://api.dumpus.app/process' from origin 'https://web.dumpus.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by Androz2091** [comment]
@DarkPizza thank you for the report. It should be working now. Can you confirm it is?

**Comment by Androz2091** [comment]
Ah, yes. I often get overwhelmed with notifications. Thank you for reporting here

**Comment by cozykitten** [comment]
umm yea.. same thing, both using web-version and cloned repo... is there a way to run 100% locally to not have to rely on the servers uptime?

**Comment by Androz2091** [comment]
Sorry guys and thank you for reporting. You can always run the API on your own (dumpus-app/dumpus-api). 
Also please if you know people that might contribute please ask them 🙏
