### ISSUE TITLE
Unsupported sql feature

### ISSUE THREAD

**Issue by florian-lefebvre** [dumpus-app/dumpus-app#37]
https://github.com/dumpus-app/dumpus-api/blob/main/docs/queries.sql#L104

generate_series is a sqlite extension. AFAIK sql.js doesn't support loading extensions at runtime, it requires to build sql.js (see https://chat.openai.com/share/e0f5535e-7e8e-4338-8781-2aa03cbc4e63)

Do we want to do this and refer to our custom build using [github aliases](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#github-urls)? Like

```json
{
	"dependencies": {
		"sql.js": "dumpus-app/sql.js"
	}
}
```

I'd prefer using something else to generate the series (or either doing it outside of sqlite) but let me know @Androz2091

**Comment by florian-lefebvre** [comment]
@Androz2091 do you think we really need this? I think filling the gaps in js is enough considering our usage. If that's the case, we can delete (or archive) our sql.js fork

**Comment by Androz2091** [comment]
definitely, yes

**Comment by Androz2091** [comment]
keep the fork alive though
